# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksmanage', '0002_auto_20170828_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='catego',
            field=models.ManyToManyField(to='booksmanage.Category'),
        ),
    ]
